blog/urls.py
from django.urls import path 
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name="blog"

urlpatterns = [
    path('', BlogListView.as_view(), name="home"),
    path('create/', BlogCreateView.as_view(), name="create"),
    path('<int:pk>/', BlogDetailView.as_view(), name="detail"),
    path('<int:pk>/update/', BlogUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name="delete")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', HomeView.as_view(), name="home"),

    path('blog/', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=250)
    content = models.TextField()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms 

from .models import Post 

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post 
        fields = ('title', 'content')

blog/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import View, UpdateView, DeleteView
from .forms import PostCreateForm
from .models import Post
from django.urls import reverse_lazy

# Create your views here.
class BlogListView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        context = {   
            'posts':posts
        }
        return render(request, 'blog_list.html', context)

class BlogCreateView(View):
    def get(self, request, *args, **kwargs):
        form = PostCreateForm()
        context = {   
            'form':form
        }
        return render(request, 'blog_create.html', context)

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            form = PostCreateForm( request.POST)
            if form.is_valid():
                title = form.cleaned_data.get('title')
                content = form.cleaned_data.get('content')

                p, created = Post.objects.get_or_create(title=title, content=content)
                p.save()
                return redirect('blog:home')
        context = {   
        }
        return render(request, 'blog_create.html', context)

class BlogDetailView(View):

    def get(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        context={
            'post':post
        }
        return render(request, 'blog_detail.html', context)

class BlogUpdateView(UpdateView):
    model = Post
    fields = ['title', 'content']
    template_name = 'blog_update.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs={'pk':pk})

class BlogDeleteView(DeleteView):
    model = Post
    template_name = 'blog_delete.html'
    success_url = reverse_lazy('blog:home')

core/views.py
from django.views.generic import View
from django.shortcuts import render

class HomeView(View): 
    def get(self, request, *args, **kwargs):
        context={
            
        }
        return render(request, 'index.html', context) 

templates/base.html
{% load tailwind_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% tailwind_css %}

    <title>Document</title>
</head>
<body>
    
    {% block content %}{% endblock content %}

</body>
</html>

templates/blog_create.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
{% csrf_token %}
<br>
<p style="padding-left:20px;">
<a class="bg-green-500 text-white font-bold py-2 px-4">Title</a>
<br>
<br>
{{form.title}}
<br>
<br>
<br>
<a class="bg-green-500 text-white font-bold py-2 px-4">Content</a>
<br>
<br>
{{form.content}}
<a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:right"><button type="submit">Submit</button></a>
</form>
</p>
{% endblock content %}

templates/blog_delete.html
{% extends 'base.html' %}

{% block content %}
<p style="padding-left:20px;">
<br>
<a class="bg-red-500 text-white">Are you sure?</a>
<br>
<br>
<form method="POST">
{% csrf_token %}
{{form.title}}
<p style="padding-left:20px;">
<a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:right"><button type="submit">Delete</button></a>
</p>
</form>
{% endblock content %}

templates/blog_detail.html
{{post.title}}
<br>
{{post.content}}

templates/blog_list.html
{% extends 'base.html' %}

{% block content %}
<br>
<p style="padding-left:20px;">
<a class="bg-green-500 text-white font-bold py-2 px-20">Blog list</a> 
<br>
<br>
{%for post in posts%}
<a class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" href="{% url 'blog:detail' post.id %}">{{post.title}}</a> 
<a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:right" href="{% url 'blog:update' post.id %}">Update</a>
<a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:right" href="{% url 'blog:delete' post.id %}">Delete</a>
<br>
<br>
{% endfor %}
<br>
<p style="padding-left:20px;">
<a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:right" href="{% url 'blog:create' %}">Create</a>
</p>
{% endblock content %}

templates/blog_update.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
{% csrf_token %}
<br>
<p style="padding-left:20px;">
<a class="bg-green-500 text-white font-bold py-2 px-4">Title</a>
<br>
<br>
{{form.title}}
<br>
<br>
<br>
<a class="bg-green-500 text-white font-bold py-2 px-4">Content</a>
<br>
<br>
{{form.content}}
<a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:right"><button type="submit">Update</button></a>
</form>
</p>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block content %} 

<br/>
<p style="padding-left:20px;">
<a class="bg-red-500 text-white">  ¡Hola! Visita mi</a> <a class="bg-gray-200 text-blue-500" href="{% url 'blog:home' %}">blog aquí</a>
</p>

{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-grey-lightest font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>